SUPPORTED_FIELDS = {
    "net": [
        "irr_as_set",
        "route_server",
        "looking_glass",
        "info_type",
        "info_types",
        "info_prefixes4",
        "info_prefixes6",
        "info_traffic",
        "info_ratio",
        "info_scope",
        "info_unicast",
        "info_multicast",
        "info_ipv6",
        "info_never_via_route_servers",
        "allow_ixp_update",
        "policy_url",
        "policy_general",
        "policy_locations",
        "policy_ratio",
        "policy_contracts",
        "status_dashboard",
    ],
    "ix": [
        "media",
        "service_level",
        "terms",
        "url_stats",
        "tech_email",
        "tech_phone",
        "sales_email",
        "policy_email",
        "policy_phone",
        "status_dashboard",
    ],
    "ixlan": [
        "mtu",
        "ixf_ixp_import_enabled",
        "ixf_ixp_member_list_url",
    ],
    "fac": [
        "address1",
        "address2",
        "suite",
        "city",
        "zipcode",
        "state",
        "country",
        "region_continent",
        "clli",
        "npanxx",
        "tech_email",
        "tech_phone",
        "sales_email",
        "sales_phone",
        "property",
        "diverse_serving_substations",
        "available_voltage_services",
    ],
    "netixlan": [
        "speed",
        "operational",
        "is_rs_peer",
    ],
    "poc": [
        "role",
        "name",
        "phone",
        "email",
    ],
}
