[flake8]
extend-ignore = E203, E266, E501, C901
exclude =
    .git,
    .venv,
    .tox,
    __pycache__,
    build,
    dist
# line length is intentionally set to 80 here because black uses Bugbear
# See https://github.com/psf/black/blob/master/docs/the_black_code_style.md#line-length for more details
max-line-length = 80
max-complexity = 18
select = B,C,E,F,W,T4,B9

per-file-ignores =
    peeringdb_server/migrations/*.py:F401
