"""
Typed key registry for object metadata (#1751).

Objects that participate in the metadata mechanism (net and netixlan at
launch) carry a single `meta` JSON document field, defined once in
django-peeringdb. Everything else lives here, server-side:

- which keys exist, and on which object types (handleref tags)
- each key's value schema and validation (pydantic value models; tunable
  bounds come from deployment settings, never code constants)
- whether a key is filterable: a filterable key declares typed generated
  columns derived from the JSON document. `contribute_generated_columns()`
  injects those columns into the concrete model at import time, so
  `makemigrations` picks them up and the API filter machinery can treat
  them like ordinary indexed fields.

Adding, changing or retiring a key is a change to REGISTRY (plus the
autogenerated migration if the key is filterable) -- no django-peeringdb
release, no API schema event.

Writes with unregistered keys are rejected (`validate_meta`). Metadata is
auxiliary data: registry validation never reads or alters the object's
concrete fields, and planned data is never reconciled with actual state.
"""

import datetime
import re
from collections.abc import Callable
from dataclasses import dataclass
from dataclasses import field as dataclass_field

from django.apps import apps as django_apps
from django.conf import settings
from django.core import checks
from django.db import models
from django.db.models.fields.json import KeyTextTransform
from django.db.models.functions import Cast
from django.utils.translation import gettext_lazy as _
from pydantic import (
    BaseModel,
    ConfigDict,
    StrictBool,
    StrictInt,
    StrictStr,
    TypeAdapter,
    field_validator,
)
from pydantic import ValidationError as PydanticValidationError
from rest_framework.exceptions import ValidationError as RestValidationError
from rest_framework.request import Request

__all__ = [
    "REGISTRY",
    "PLANNED_STATUS_CHANGE_STATUSES",
    "MetaKey",
    "GeneratedColumn",
    "keys_for_tag",
    "validate_meta",
    "clean_meta",
    "contribute_generated_columns",
    "filter_column_map",
]


# --- value models -----------------------------------------------------------
#
# Bounds are read inside validators (not at class definition) so the
# `set_option()` deployment overrides in mainsite settings apply.


class PlannedStatusChange(BaseModel):
    """
    Value model for `planned_status_change` (#1742, #1736).

    A pure declaration of intent about the object's `status` field: the key
    is named for the field it targets and speaks that field's value
    vocabulary. Setting or clearing it has no effect on the object's actual
    status, and nothing the object does alters the plan.
    """

    model_config = ConfigDict(extra="forbid")

    status: str
    date: datetime.date

    @field_validator("status")
    @classmethod
    def validate_status(cls, value):
        if value not in PLANNED_STATUS_CHANGE_STATUSES:
            raise ValueError(
                "status must be one of: " + ", ".join(PLANNED_STATUS_CHANGE_STATUSES)
            )
        return value

    @field_validator("date")
    @classmethod
    def validate_date(cls, value, info):
        # The future/window bound is a WRITE-TIME bound: it constrains the
        # moment a plan is set, not the plan's continued validity. It must
        # therefore only be applied to a value the caller is actually
        # writing -- see `validate_meta` for why every write path
        # re-submits an unchanged document, and what re-applying this to
        # such a value would do.
        if not (info.context or {}).get("changed", True):
            return value
        today = datetime.date.today()
        window = settings.META_PLANNED_STATUS_CHANGE_WINDOW_DAYS
        if value <= today:
            raise ValueError("date must be in the future")
        if value > today + datetime.timedelta(days=window):
            raise ValueError(f"date must be at most {window} days ahead")
        return value


def _validate_preferred_ip_mtu(value: int) -> int:
    lo = settings.META_PREFERRED_IP_MTU_MIN
    hi = settings.META_PREFERRED_IP_MTU_MAX
    if not lo <= value <= hi:
        raise ValueError(f"must be between {lo} and {hi}")
    return value


# status values a `planned_status_change` may target on a netixlan:
# "deleted" (the network is leaving the IXP) or "ok" (the connection goes
# live on that date). Read by the value model below and by the UI enum the
# dashboard's select loads -- the registry stays the single source of truth,
# so this vocabulary never needs a django-peeringdb release.
PLANNED_STATUS_CHANGE_STATUSES = ("ok", "deleted")


# standard (16bit:16bit) or large (32bit:32bit:32bit) BGP community.
# [0-9] rather than \d: \d also matches non-ASCII decimal digits, which int()
# happily parses, so "٦٥:٦" would validate and be stored as a
# community string no BGP implementation can parse.
_RTBH_COMMUNITY_REGEX = re.compile(r"^[0-9]{1,10}(:[0-9]{1,10}){1,2}$")


def _validate_rtbh_community(value: str) -> str:
    value = value.strip()
    if not _RTBH_COMMUNITY_REGEX.match(value):
        raise ValueError(
            "must be a BGP community in standard (asn:value) "
            "or large (asn:local1:local2) format"
        )
    parts = [int(part) for part in value.split(":")]
    limit = 0xFFFF if len(parts) == 2 else 0xFFFFFFFF
    if any(part > limit for part in parts):
        raise ValueError(f"community parts must be at most {limit}")
    # canonical form: the key is not filterable, so consumers compare these
    # strings client-side and "065000:0666" must not read as a different
    # community from "65000:666"
    return ":".join(str(part) for part in parts)


# --- registry plumbing ------------------------------------------------------


@dataclass(frozen=True)
class GeneratedColumn:
    """
    A typed, indexed database column derived from the `meta` JSON document.

    Declared on a filterable key; injected into the concrete model by
    `contribute_generated_columns()`. `json_path` addresses into the
    document; `output_field` builds a fresh Django field instance per model
    (field instances cannot be shared across models).
    """

    name: str  # model field / db column name
    json_path: tuple[str, ...]
    output_field: "type[models.Field] | None" = None
    output_field_kwargs: dict = dataclass_field(default_factory=dict)

    def build_field(self):
        # walk the json path: meta -> key -> subkey, unquoting to text
        expression = "meta"
        for path_key in self.json_path:
            expression = KeyTextTransform(path_key, expression)
        output = self.output_field(**self.output_field_kwargs)
        if isinstance(output, models.BooleanField):
            # text-cast of a JSON boolean is the string "true"/"false" --
            # compare against the JSON value instead of casting
            expression = models.Q(**{f"meta__{'__'.join(self.json_path)}": True})
        else:
            expression = Cast(expression, output_field=output)
        return models.GeneratedField(
            expression=expression,
            output_field=output,
            db_persist=True,
            db_index=True,
        )


@dataclass(frozen=True)
class MetaKey:
    """
    A registered metadata key: the registration is the contract.
    """

    name: str
    tags: tuple[str, ...]  # handleref tags this key applies to
    adapter: "type[BaseModel] | _FunctionAdapter"
    columns: tuple[GeneratedColumn, ...] = ()
    # Optional per-key write gate, for a key whose write permission is
    # narrower than "may edit this object" -- none of the launch keys need
    # one, since they are all owner-set voluntary data and the parent
    # endpoint has already enforced the object's normal edit permissions.
    #
    # The callback receives the requesting request, which may be None:
    # `validate_meta` is only ever called from serializer validation, so no
    # production write path arrives without one, but a serializer used
    # without request context does. A permission gate with no identifiable
    # actor DENIES -- write the callback accordingly and do not treat a
    # missing request as an internal-write escape hatch. Code that must set
    # a gated key outside a request writes the model field directly; the
    # model-layer check (`clean_meta`) validates the value but does not
    # apply this gate, since there is no actor to identify there.
    #
    # The gate applies to a *change* of the value, not to its presence in
    # the submitted document: re-submitting the stored value unchanged is
    # not a write of it, and gating that would lock the whole object for
    # anyone who fails the gate.
    writer_check: "Callable[[Request | None], bool] | None" = None

    @property
    def filterable(self):
        return bool(self.columns)

    def validate(self, value, context=None):
        """
        Validate and JSON-normalize one value. Raises ValueError.

        `context` is handed to the value model, which is how write-time
        bounds learn whether this value is actually being written -- see
        `validate_meta`.
        """
        try:
            if isinstance(self.adapter, _FunctionAdapter):
                return self.adapter.validate(value, context=context)
            instance = self.adapter.model_validate(value, context=context)
            return instance.model_dump(mode="json")
        except PydanticValidationError as exc:
            errors = "; ".join(
                "{}: {}".format(
                    ".".join(str(loc) for loc in error["loc"]) or self.name,
                    error["msg"],
                )
                for error in exc.errors()
            )
            raise ValueError(errors)


class _FunctionAdapter:
    """TypeAdapter-alike wrapping a strict base type plus a plain validator."""

    def __init__(self, base_type, func=None):
        self._adapter = TypeAdapter(base_type)
        self._func = func

    def validate(self, value, context=None):
        validated = self._adapter.validate_python(value, context=context)
        if self._func:
            validated = self._func(validated)
        return self._adapter.dump_python(validated, mode="json")


# --- the registry -----------------------------------------------------------

REGISTRY: "dict[str, MetaKey]" = {}


def register(key: MetaKey):
    REGISTRY[key.name] = key
    return key


register(
    MetaKey(
        name="planned_status_change",
        tags=("netixlan",),
        adapter=PlannedStatusChange,
        columns=(
            GeneratedColumn(
                name="meta_planned_status_change_status",
                json_path=("planned_status_change", "status"),
                output_field=models.CharField,
                output_field_kwargs={"max_length": 32, "null": True},
            ),
            GeneratedColumn(
                name="meta_planned_status_change_date",
                json_path=("planned_status_change", "date"),
                output_field=models.DateField,
                output_field_kwargs={"null": True},
            ),
        ),
    )
)

register(
    MetaKey(
        name="rfc8950",
        tags=("netixlan",),
        adapter=_FunctionAdapter(StrictBool),
        columns=(
            GeneratedColumn(
                name="meta_rfc8950",
                json_path=("rfc8950",),
                output_field=models.BooleanField,
                output_field_kwargs={"null": True},
            ),
        ),
    )
)

register(
    MetaKey(
        name="preferred_ip_mtu",
        tags=("net",),
        adapter=_FunctionAdapter(StrictInt, _validate_preferred_ip_mtu),
    )
)

register(
    MetaKey(
        name="rtbh_community",
        tags=("net",),
        adapter=_FunctionAdapter(StrictStr, _validate_rtbh_community),
    )
)


# --- public api -------------------------------------------------------------


def keys_for_tag(tag: str) -> "dict[str, MetaKey]":
    return {name: key for name, key in REGISTRY.items() if tag in key.tags}


def _validate_document(tag: str, meta, *, request=None, current=None, write=True):
    """
    Shared body of `validate_meta` and `clean_meta`: returns
    `(normalized_document, errors)` and never raises for a bad value.
    `errors` is a `{key: message}` dict, or a bare message when the
    document itself is not an object, or None when there is nothing wrong.

    `write` separates the two callers. A write (the API) applies write-time
    bounds and per-key writer gates, both only to the keys whose value
    actually changes. A structural check (the model layer) applies neither:
    it asks only whether the document can be stored, the object's own
    permission check has already happened by then, and re-applying a
    write-time bound to an unchanged value is exactly the lock
    `validate_meta` describes.
    """

    if meta is None:
        return {}, None
    if not isinstance(meta, dict):
        return {}, _("must be an object")

    registered = keys_for_tag(tag)
    errors = {}
    normalized = {}

    for name, value in meta.items():
        key = registered.get(name)
        if key is None:
            errors[name] = _("unregistered metadata key")
            continue
        changed = write and (current is None or current.get(name) != value)
        # the writer gate follows `changed` for the same reason the
        # write-time bounds do (see `validate_meta`): every write path
        # re-submits the whole document, so a key that is merely
        # round-tripped is not being set. Gating it unconditionally would
        # make an object carrying an already-set gated key uneditable by
        # anyone who fails the gate -- not just unwritable for that key.
        if changed and key.writer_check and not key.writer_check(request):
            errors[name] = _("not permitted to set this key")
            continue
        try:
            normalized[name] = key.validate(value, context={"changed": changed})
        except (ValueError, PydanticValidationError) as exc:
            errors[name] = str(exc)

    return normalized, errors or None


def validate_meta(tag: str, meta, request=None, current=None) -> dict:
    """
    Validate a full `meta` document for an object type against the registry.

    Returns the JSON-normalized document. Raises RestValidationError with
    per-key messages; unregistered keys are rejected outright.

    `request` is passed to any key declaring a `writer_check`. It may be
    None (a serializer used without request context), in which case a gated
    key is denied -- see `MetaKey.writer_check`.

    `current` is the object's stored document, when it has one. A key whose
    incoming value is identical to the stored one is not a write of that
    value, so it is exempt from write-time bounds (currently only
    `planned_status_change.date` has one). That exemption is load bearing,
    not a convenience: every write path re-submits the whole document --
    the dashboard exports every field in a netixlan row as soon as one of
    them changes, and an API PUT round-trips `meta` because `meta` is the
    read surface -- so without it, a plan whose date has passed would
    reject every subsequent edit of the object, and since the window is
    finite every plan eventually reaches that state. A plan is a
    declaration that persists until the network edits it (#1742), not a
    lock on the row.
    """

    normalized, errors = _validate_document(
        tag, meta, request=request, current=current, write=True
    )
    if errors:
        raise RestValidationError({"meta": errors})

    return normalized


def clean_meta(tag: str, meta) -> "tuple[dict, dict | str | None]":
    """
    Registry validation for the model layer -- `full_clean()`, and through
    it the Django admin (where `meta` is a free-text JSON box) and
    management commands.

    Returns `(normalized_document, errors)` -- errors being a
    `{key: message}` dict (or a bare message for a non-object document, or
    None when the document is clean), leaving the caller to raise its own
    ValidationError flavor. Same split as `clean_ixp_update_exclude()` in
    validators.py.

    Write-time bounds and per-key writer gates are NOT applied here. This
    runs on every save, including the IX-F importer's, where the document is
    usually untouched; applying the bounds would recreate exactly the lock
    `validate_meta` describes, and applying the gates would make a gated key
    unsavable outside a request. The serializers own both, because they are
    the only layer that knows what changed and who is asking.
    """

    return _validate_document(tag, meta, write=False)


def contribute_generated_columns(model_cls, tag: str):
    """
    Inject the generated columns for all filterable keys registered on
    `tag` into a concrete model. Called at the bottom of the model's class
    definition in models.py; picked up by makemigrations from there.
    """

    for key in keys_for_tag(tag).values():
        for column in key.columns:
            model_cls.add_to_class(column.name, column.build_field())


def filter_column_map(tag: str) -> "dict[str, str]":
    """
    Maps public API filter prefixes (`meta__<path>`) onto the generated
    column names, for the serializer query-param rewrite.
    """

    mapping = {}
    for key in keys_for_tag(tag).values():
        for column in key.columns:
            mapping["meta__" + "__".join(column.json_path)] = column.name
    return mapping


# --- registry <-> schema drift check ----------------------------------------

# handleref tag -> concrete model participating in the metadata mechanism
PARTICIPATING_MODELS = {
    "netixlan": ("peeringdb_server", "NetworkIXLan"),
    "net": ("peeringdb_server", "Network"),
}


def check_meta_registry(app_configs, **kwargs):
    """
    System check: the registry and the model schema must agree.

    Every generated column a registered key declares must exist on its
    model, and every `meta_`-prefixed model field must be declared by the
    registry (a retired key must take its column's removal migration with
    it). Model <-> database drift is covered by `makemigrations --check`
    in CI; together the two make registry drift fail loudly.
    """

    errors = []

    for tag, (app_label, model_name) in PARTICIPATING_MODELS.items():
        model = django_apps.get_model(app_label, model_name)
        model_fields = {field.name for field in model._meta.get_fields()}
        declared = {
            column.name for key in keys_for_tag(tag).values() for column in key.columns
        }

        for name in sorted(declared - model_fields):
            errors.append(
                checks.Error(
                    f"metadata registry declares generated column '{name}' "
                    f"on {model_name} but the model does not have it",
                    hint="contribute_generated_columns() call missing or broken",
                    id="peeringdb_server.E101",
                )
            )

        leftover = {
            name
            for name in model_fields - declared
            if name.startswith("meta_") and name != "meta"
        }
        for name in sorted(leftover):
            errors.append(
                checks.Error(
                    f"{model_name} has metadata column '{name}' that no "
                    "registered key declares",
                    hint=(
                        "retiring a key must remove its generated column "
                        "(migration) along with the registry declaration"
                    ),
                    id="peeringdb_server.E102",
                )
            )

    return errors
