# Generated by Django 1.11.4 on 2017-08-30 15:27


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0004_geocode_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facility",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="facility",
            old_name="lon",
            new_name="longitude",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="lon",
            new_name="longitude",
        ),
    ]
