# Generated by Django 1.11.4 on 2017-10-20 08:12


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reversion", "0001_squashed_0004_auto_20160611_1202"),
        ("peeringdb_server", "0007_ixlan_json_member_list_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="IXLanIXFMemberImportAttempt",
            fields=[
                (
                    "ixlan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ixf_import_attempt",
                        serialize=False,
                        to="peeringdb_server.IXLan",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IXLanIXFMemberImportLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "ixlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ixf_import_log_set",
                        to="peeringdb_server.IXLan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IXLanIXFMemberImportLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="peeringdb_server.IXLanIXFMemberImportLog",
                    ),
                ),
                (
                    "netixlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ixf_import_log_entries",
                        to="peeringdb_server.NetworkIXLan",
                    ),
                ),
                (
                    "version_after",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ixf_import_log_after",
                        to="reversion.Version",
                    ),
                ),
                (
                    "version_before",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ixf_import_log_before",
                        to="reversion.Version",
                    ),
                ),
            ],
        ),
    ]
