# Generated by Django 1.11.4 on 2017-11-08 10:34


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0010_rename_ixf_ixp_member_list_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandLineTool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[(b"pdb_renumber_lans", "Renumber IP Space")],
                        help_text="name of the tool",
                        max_length=255,
                    ),
                ),
                (
                    "arguments",
                    models.TextField(
                        help_text="json serialization of arguments and options passed"
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, help_text="result log", null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text=b"command was run at this date and time",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text=b"the user that ran this command",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clt_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
