# Generated by Django 1.11.23 on 2020-01-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0021_sponsorship_drop_single_org_relation_fields"),
    ]

    operations = [
        # this change was reverted, but we will keep this empty migration
        # so it does not break the migration chain
    ]
