# Generated by Django 1.11.23 on 2020-01-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0027_never_via_route_servers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ixlan",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
