# Generated by Django 2.2.9 on 2020-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0033_fac_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkixlan",
            name="operational",
            field=models.BooleanField(default=True),
        ),
    ]
