# Generated by Django 2.2.13 on 2020-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0040_ixf_member_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ixlan",
            name="ixf_ixp_import_error",
            field=models.TextField(
                blank=True,
                help_text="Reason IX-F data could not be parsed",
                null=True,
                verbose_name="IX-F error",
            ),
        ),
        migrations.AddField(
            model_name="ixlan",
            name="ixf_ixp_import_error_notified",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time we notified the exchange about the IX-F parsing issue",
                null=True,
                verbose_name="IX-F error notification date",
            ),
        ),
    ]
