# Generated by Django 2.2.14 on 2020-07-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0046_ixfmemberdata_requirement_of"),
    ]

    operations = [
        migrations.CreateModel(
            name="IXFImportEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("recipients", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("sent", models.DateTimeField(blank=True, null=True)),
                (
                    "ix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ix_email_set",
                        to="peeringdb_server.InternetExchange",
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "net",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_email_set",
                        to="peeringdb_server.Network",
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "IXF Import Email",
                "verbose_name_plural": "IXF Import Emails",
            },
        ),
    ]
