# Generated by Django 2.2.17 on 2020-11-17 13:10

from django.db import migrations

# django-namespaces-perms has been removed entirely
# this migration used to move nsp permissions to the
# grainy framework.
#
# empty migration until we squash


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0059_ixf_typos"),
    ]

    operations = []
