# Generated by Django 2.2.16 on 2020-11-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0060_nsp_to_grainy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="sales_phone",
            field=models.CharField(
                blank=True,
                help_text="An E.164-formatted phone number starts with a +, followed by the country code, then the national phone number (dropping the leading 0 in most countries), without spaces or dashes between the groups of digits",
                max_length=192,
                verbose_name="Sales Phone",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="tech_phone",
            field=models.CharField(
                blank=True,
                help_text="An E.164-formatted phone number starts with a +, followed by the country code, then the national phone number (dropping the leading 0 in most countries), without spaces or dashes between the groups of digits",
                max_length=192,
                verbose_name="Technical Phone",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="policy_phone",
            field=models.CharField(
                blank=True,
                help_text="An E.164-formatted phone number starts with a +, followed by the country code, then the national phone number (dropping the leading 0 in most countries), without spaces or dashes between the groups of digits",
                max_length=192,
                verbose_name="Policy Phone",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="tech_phone",
            field=models.CharField(
                blank=True,
                help_text="An E.164-formatted phone number starts with a +, followed by the country code, then the national phone number (dropping the leading 0 in most countries), without spaces or dashes between the groups of digits",
                max_length=192,
                verbose_name="Technical Phone",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="allow_ixp_update",
            field=models.BooleanField(
                default=False,
                help_text="Specifies whether an IXP is allowed to add a netixlan entry for this network via their ixp_member data",
            ),
        ),
        migrations.AlterField(
            model_name="networkcontact",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="An E.164-formatted phone number starts with a +, followed by the country code, then the national phone number (dropping the leading 0 in most countries), without spaces or dashes between the groups of digits",
                max_length=100,
                verbose_name="Phone",
            ),
        ),
    ]
