# Generated by Django 3.2.5 on 2021-07-30 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0072_geocoordinatecache"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetexchange",
            name="ixf_import_request",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of most recent manual import request",
                null=True,
                verbose_name="Manual IX-F import request",
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="ixf_import_request_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("importing", "Importing"),
                    ("finished", "Finished"),
                ],
                default="queued",
                help_text="The current status of the manual IX-F import request",
                max_length=32,
                verbose_name="Manual IX-F import status",
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="ixf_import_request_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that triggered the manual IX-F import request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_ixf_imports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
