# Generated by Django 3.2.12 on 2022-03-23 05:43

import django.core.validators
import django_inet.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0081_status_dashboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentsetting",
            name="setting",
            field=models.CharField(
                choices=[
                    ("API_THROTTLE_RATE_ANON", "API: Anonymous user API throttle rate"),
                    (
                        "API_THROTTLE_RATE_USER",
                        "API: Authenticated user API throttle rate",
                    ),
                    (
                        "API_THROTTLE_RATE_ANON_MSG",
                        "API: Anonymous user API throttle rate message",
                    ),
                    (
                        "API_THROTTLE_RATE_USER_MSG",
                        "API: User API throttle rate message",
                    ),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
