# Generated by Django 3.2.16 on 2022-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0100_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationapikey",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userapikey",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=16,
            ),
        ),
    ]
