# Generated by Django 3.2.16 on 2022-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0101_api_key_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(fields=["status"], name="fac_status"),
        ),
        migrations.AddIndex(
            model_name="internetexchange",
            index=models.Index(fields=["status"], name="ix_status"),
        ),
        migrations.AddIndex(
            model_name="network",
            index=models.Index(
                fields=["status", "allow_ixp_update"], name="net_status"
            ),
        ),
        migrations.AddIndex(
            model_name="networkfacility",
            index=models.Index(fields=["status"], name="netfac_status"),
        ),
        migrations.AddIndex(
            model_name="networkixlan",
            index=models.Index(fields=["status"], name="netixlan_status"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["status"], name="org_status"),
        ),
    ]
