# Generated by Django 3.2.16 on 2022-12-09 12:19

from django.db import migrations, models


def update_mtu_zero(apps, schema_editor):
    IXLan = apps.get_model("peeringdb_server", "IXLan")

    for ixlan in IXLan.handleref.all():
        if not ixlan.mtu:
            ixlan.mtu = 1500
            ixlan.save()


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0102_indexes"),
    ]

    operations = [
        migrations.RunPython(update_mtu_zero, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ixlan",
            name="mtu",
            field=models.PositiveIntegerField(default=1500, verbose_name="MTU"),
        ),
    ]
