# Generated by Django 3.2.16 on 2023-01-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0105_carrier_website_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="primary_org",
            field=models.IntegerField(
                blank=True, help_text="The user's primary organization", null=True
            ),
        ),
    ]
