# Generated by Django 3.2.18 on 2023-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0109_auto_20230317_1054"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="social_media",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Media"
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="social_media",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Media"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="social_media",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Media"
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="social_media",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Media"
            ),
        ),
        migrations.AddField(
            model_name="network",
            name="social_media",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Media"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="social_media",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Media"
            ),
        ),
    ]
