# Generated by Django 4.2.2 on 2023-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0112_organization_require_totpdevice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="last_notified",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the organization admins were notified about 2FA",
                null=True,
            ),
        ),
    ]
