# Generated by Django 4.2.4 on 2023-09-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0116_alter_facility_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="periodic_reauth_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1w", "1 Week"),
                    ("2w", "2 Weeks"),
                    ("1m", "1 Month"),
                    ("3m", "3 Month"),
                    ("6m", "6 Months"),
                    ("1y", "1 Year"),
                ],
                default="3m",
                help_text="Range of options is available:\n1 Week, 2 Weeks, 1 Month, \n3 Month, 6 Month, 1 Year",
                max_length=255,
                null=True,
            ),
        ),
    ]
