# Generated by Django 4.2.6 on 2023-11-22 15:53

import django_peeringdb.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "peeringdb_server",
            "0117_periodic_reauth_period",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="info_types",
            field=django_peeringdb.fields.MultipleChoiceField(
                blank=True,
                choices=[
                    ("NSP", "NSP"),
                    ("Content", "Content"),
                    ("Cable/DSL/ISP", "Cable/DSL/ISP"),
                    ("Enterprise", "Enterprise"),
                    ("Educational/Research", "Educational/Research"),
                    ("Non-Profit", "Non-Profit"),
                    ("Route Server", "Route Server"),
                    ("Network Services", "Network Services"),
                    ("Route Collector", "Route Collector"),
                    ("Government", "Government"),
                ],
                max_length=255,
                verbose_name="Network Types",
            ),
        ),
    ]
