# Generated by Django 4.2.6 on 2023-11-23 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0119_network_type_clobber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="network",
            name="info_type",
        ),
    ]
