# Generated by Django 4.2.9 on 2024-02-15 10:33

import django_peeringdb.models.abstract
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0123_notified_for_geocoords"),
    ]

    operations = [
        migrations.AddField(
            model_name="ixfmemberdata",
            name="bfd_support",
            field=models.BooleanField(default=False, verbose_name="BFD support"),
        ),
        migrations.AddField(
            model_name="networkixlan",
            name="bfd_support",
            field=models.BooleanField(default=False, verbose_name="BFD support"),
        ),
    ]
