# Generated by Django 4.2.11 on 2024-04-02 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        ("peeringdb_server", "0126_update_twitter_to_x"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOrgAffiliationRequestHistory",
            fields=[],
            options={
                "verbose_name": "User to Organization Affiliation Request History",
                "verbose_name_plural": "User to Organization Affiliation Request History",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reversion.version",),
        ),
    ]
