# Generated by Django 4.2.11 on 2024-04-26 10:28

import django_peeringdb.fields
import django_peeringdb.models.abstract
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0128_add_info_traffic_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="property",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Disclosed"),
                    ("Owner", "Owner"),
                    ("Lessee", "Leased or Rented"),
                ],
                help_text="Leasing or renting is an agreement with a property owner for use of the property.",
                max_length=27,
                null=True,
                verbose_name="Property",
            ),
        )
    ]
