# Generated by Django 4.2.16 on 2024-09-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0133_alter_ix_media_field_add_default_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkixlan",
            name="net_side",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="net_side_set",
                to="peeringdb_server.facility",
            ),
        ),
        migrations.AddField(
            model_name="networkixlan",
            name="ix_side",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ix_side_set",
                to="peeringdb_server.facility",
            ),
        ),
    ]
