# Generated by Django 4.2.18 on 2025-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0136_alter_environmentsetting_setting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="opt_flags",
            field=models.IntegerField(
                default=0,
                help_text="Bitmask to store user preference toggles",
                verbose_name="option flags",
            ),
        ),
    ]
