# Generated by Django 4.2.20 on 2025-04-15 09:07

from django.db import migrations, models


def deduplicate_networkfacility(apps, schema_editor):
    """
    Find and deduplicate NetworkFacility entries that would violate the new
    unique_together constraint (net, fac).

    Keep the most recently updated entry for each (net, fac) pair.
    """
    NetworkFacility = apps.get_model("peeringdb_server", "NetworkFacility")

    # Get all NetworkFacility objects
    all_netfacs = NetworkFacility.handleref.all()

    # Track seen (net_id, fac_id) pairs
    pairs = {}
    to_delete = []

    for netfac in all_netfacs:
        key = (netfac.network_id, netfac.facility_id)
        pairs.setdefault(key, []).append(netfac)

    for key, netfacs in pairs.items():
        if len(netfacs) == 1:
            continue

        # first delete all with status != "ok"
        for netfac in list(netfacs):
            if netfac.status != "ok":
                to_delete.append(netfac)
                netfacs.remove(netfac)

        # then delete the rest, leaving one
        for netfac in netfacs[1:]:
            to_delete.append(netfac)

    # Delete duplicates
    for netfac in to_delete:
        netfac.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0137_user_opt_flags"),
    ]

    operations = [
        # First run the deduplication function
        migrations.RunPython(
            deduplicate_networkfacility, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="environmentsetting",
            name="setting",
            field=models.CharField(
                choices=[
                    ("API_THROTTLE_RATE_ANON", "API: Anonymous API throttle rate"),
                    ("API_THROTTLE_RATE_USER", "API: Authenticated API throttle rate"),
                    (
                        "API_THROTTLE_MELISSA_RATE_ADMIN",
                        "API: Melissa request throttle rate for admin users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_ADMIN",
                        "API: Melissa request throttle enabled for admin users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_RATE_USER",
                        "API: Melissa request throttle rate for users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_USER",
                        "API: Melissa request throttle enabled for users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_RATE_ORG",
                        "API: Melissa request throttle rate for organizations",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_ORG",
                        "API: Melissa request throttle enabled for organizations",
                    ),
                    (
                        "API_THROTTLE_MELISSA_RATE_IP",
                        "API: Melissa request throttle rate for anonymous requests (ips)",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_IP",
                        "API: Melissa request throttle enabled for anonymous requests (ips)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_CIDR",
                        "API: Repeated request throttle size threshold for ip blocks (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_CIDR",
                        "API: Repeated request throttle rate for ip blocks",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_CIDR",
                        "API: Repeated request throttle enabled for ip blocks",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_IP",
                        "API: Repeated request throttle size threshold for ip addresses (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_IP",
                        "API: Repeated request throttle rate for ip addresses",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_IP",
                        "API: Repeated request throttle enabled for ip addresses",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_USER",
                        "API: Repeated request throttle size threshold for authenticated users (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_USER",
                        "API: Repeated request throttle rate for authenticated users",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_USER",
                        "API: Repeated request throttle enabled for authenticated users",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_ORG",
                        "API: Repeated request throttle size threshold for organization api-keys (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_ORG",
                        "API: Repeated request throttle rate for organization api-keys",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_ORG",
                        "API: Repeated request throttle enabled for organization api-keys",
                    ),
                    (
                        "API_THROTTLE_RATE_ANON_MSG",
                        "API: Anonymous API throttle rate message",
                    ),
                    (
                        "API_THROTTLE_RATE_USER_MSG",
                        "API: Authenticated API throttle rate message",
                    ),
                    ("API_THROTTLE_RATE_WRITE", "API: Request Write API Limiting"),
                    (
                        "API_THROTTLE_ORGANIZATION_USERS",
                        "API: Request Organization Users API Limiting",
                    ),
                    ("DATABASE_LAST_SYNC", "Show last database sync"),
                    ("TUTORIAL_MODE_MESSAGE", "Tutorial mode banner message"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="networkfacility",
            unique_together={("network", "facility")},
        ),
        migrations.RemoveField(
            model_name="networkfacility",
            name="local_asn",
        ),
    ]
