# Generated by Django 4.2.21 on 2025-05-12 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0138_alter_environmentsetting_setting"),
        ("peeringdb_server", "0138_alter_environmentsetting_setting_and_more"),
    ]

    operations = []
