# Generated by Django 4.2.23 on 2025-06-17 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0139_merge_20250512_1658"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("authenticated", models.BooleanField(default=False)),
                ("version", models.SmallIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Search Log",
                "verbose_name_plural": "Search Logs",
                "db_table": "peeringdb_search_log",
            },
        ),
    ]
