# Generated by Django 5.2.4 on 2025-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0140_searchlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AddField(
            model_name="network",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
    ]
