# Generated by Django 5.2.5 on 2025-09-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0141_campus_logo_carrier_logo_facility_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="locale",
            field=models.CharField(
                choices=[
                    ("cs-cz", "Czech"),
                    ("de-de", "German"),
                    ("el-gr", "Greek"),
                    ("en", "English"),
                    ("es-es", "Spanish"),
                    ("fr-fr", "French"),
                    ("it", "Italian"),
                    ("ja-jp", "Japanese"),
                    ("lt", "Lithuanian"),
                    ("oc", "Occitan"),
                    ("pt", "Portuguese"),
                    ("ro-ro", "Romanian"),
                    ("ru-ru", "Russian"),
                    ("zh-cn", "Chinese (Simplified)"),
                    ("zh-tw", "Chinese (Traditional)"),
                ],
                default="en",
                max_length=62,
                verbose_name="language",
            ),
        ),
    ]
