# Generated by Django 5.2.4 on 2025-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0142_alter_user_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this organization",
                max_length=200,
                null=True,
            ),
        ),
    ]