# Generated by Django 5.2.6 on 2025-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0142_alter_user_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="carrier_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="number of carriers at this facility",
                verbose_name="number of carriers at this facility",
            ),
        ),
    ]
