# Generated by Django 5.2.8 on 2026-01-09 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0142_alter_user_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="last_notified",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="require_2fa",
        ),
    ]
