# Generated by Django 5.2.7 on 2025-11-19 11:21

from django.db import migrations, models

import peeringdb_server.validators


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0142_alter_user_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=254,
                validators=[peeringdb_server.validators.validate_account_name],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=254,
                validators=[peeringdb_server.validators.validate_account_name],
                verbose_name="last name",
            ),
        ),
    ]
