# Generated by Django 6.0.1 on 2026-01-19 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0143_alter_user_first_name_alter_user_last_name"),
        ("peeringdb_server", "0143_facility_carrier_count"),
    ]

    operations = []
