# Generated by Django 5.2.10 on 2026-01-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0144_merge_20260119_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                max_length=255,
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                max_length=255,
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                max_length=255,
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                max_length=255,
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this object.",
                max_length=255,
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this organization",
                max_length=255,
                null=True,
                upload_to="logos_user_supplied/",
            ),
        ),
        migrations.AlterField(
            model_name="partnership",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this partnership",
                max_length=255,
                null=True,
                upload_to="logos/",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshiporganization",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Allows you to upload and set a logo image file for this sponsorship",
                max_length=255,
                null=True,
                upload_to="logos/",
            ),
        ),
    ]
