# Generated by Django 5.2.10 on 2026-02-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0145_alter_campus_logo_alter_carrier_logo_and_more"),
        ("peeringdb_server", "0143_remove_organization_last_notified_and_more"),
    ]

    operations = []
