# Generated by Django 5.2.12 on 2026-03-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0147_alter_environmentsetting_setting'),
        ('peeringdb_server', '0147_ixfmemberdata_ix_side'),
    ]

    operations = [
    ]
