# Generated by Django 5.2.14 on 2026-06-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0150_organization_org_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="fac_count",
            field=models.PositiveIntegerField(default=0, help_text="Facility count"),
        ),
        migrations.AlterField(
            model_name="environmentsetting",
            name="setting",
            field=models.CharField(
                choices=[
                    ("API_THROTTLE_RATE_ANON", "API: Anonymous API throttle rate"),
                    ("API_THROTTLE_RATE_USER", "API: Authenticated API throttle rate"),
                    (
                        "API_THROTTLE_MELISSA_RATE_ADMIN",
                        "API: Melissa request throttle rate for admin users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_ADMIN",
                        "API: Melissa request throttle enabled for admin users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_RATE_USER",
                        "API: Melissa request throttle rate for users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_USER",
                        "API: Melissa request throttle enabled for users",
                    ),
                    (
                        "API_THROTTLE_MELISSA_RATE_ORG",
                        "API: Melissa request throttle rate for organizations",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_ORG",
                        "API: Melissa request throttle enabled for organizations",
                    ),
                    (
                        "API_THROTTLE_MELISSA_RATE_IP",
                        "API: Melissa request throttle rate for anonymous requests (ips)",
                    ),
                    (
                        "API_THROTTLE_MELISSA_ENABLED_IP",
                        "API: Melissa request throttle enabled for anonymous requests (ips)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_CIDR",
                        "API: Repeated request throttle size threshold for ip blocks (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_CIDR",
                        "API: Repeated request throttle rate for ip blocks",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_CIDR",
                        "API: Repeated request throttle enabled for ip blocks",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_IP",
                        "API: Repeated request throttle size threshold for ip addresses (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_IP",
                        "API: Repeated request throttle rate for ip addresses",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_IP",
                        "API: Repeated request throttle enabled for ip addresses",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_USER",
                        "API: Repeated request throttle size threshold for authenticated users (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_USER",
                        "API: Repeated request throttle rate for authenticated users",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_USER",
                        "API: Repeated request throttle enabled for authenticated users",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_THRESHOLD_ORG",
                        "API: Repeated request throttle size threshold for organization api-keys (bytes)",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_RATE_ORG",
                        "API: Repeated request throttle rate for organization api-keys",
                    ),
                    (
                        "API_THROTTLE_REPEATED_REQUEST_ENABLED_ORG",
                        "API: Repeated request throttle enabled for organization api-keys",
                    ),
                    (
                        "API_THROTTLE_RATE_ANON_MSG",
                        "API: Anonymous API throttle rate message",
                    ),
                    (
                        "API_THROTTLE_RATE_USER_MSG",
                        "API: Authenticated API throttle rate message",
                    ),
                    ("API_THROTTLE_RATE_WRITE", "API: Request Write API Limiting"),
                    (
                        "API_THROTTLE_ORGANIZATION_USERS",
                        "API: Request Organization Users API Limiting",
                    ),
                    ("RATELIMIT_WEB_PAGE_RATE", "Web: Anonymous web page rate limit"),
                    ("DATABASE_LAST_SYNC", "Show last database sync"),
                    ("TUTORIAL_MODE_MESSAGE", "Tutorial mode banner message"),
                    (
                        "NOTIFICATION_BANNER_CONTENT",
                        "Notification banner content (HTML)",
                    ),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="speed",
            field=models.PositiveIntegerField(verbose_name="Capacity (mbit/sec)"),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="speed",
            field=models.PositiveIntegerField(verbose_name="Capacity (mbit/sec)"),
        ),
    ]
