# Generated by Django 5.2.13 on 2026-05-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0150_organization_org_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskproticket',
            name='close_requested',
            field=models.BooleanField(default=False, help_text='Set when the related pending object was deleted and the ticket should be auto-closed on the DeskPRO side (#1948). Processed asynchronously by pdb_deskpro_publish.'),
        ),
        migrations.AddField(
            model_name='deskproticket',
            name='closed',
            field=models.DateTimeField(blank=True, help_text='When the auto-close request was processed', null=True),
        ),
        migrations.AddField(
            model_name='verificationqueueitem',
            name='deskpro_ticket',
            field=models.ForeignKey(blank=True, help_text='DeskPRO ticket created when this item entered the queue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vq_items', to='peeringdb_server.deskproticket'),
        ),
    ]
