# Generated by Django 5.2.14 on 2026-06-03 23:59

from django.db import migrations
from django.db.models import Count, F, Q


def populate_carrier_fac_counts(apps, schema_editor):
    Carrier = apps.get_model("peeringdb_server", "Carrier")

    Carrier._default_manager.annotate(
        actual_count=Count(
            "carrierfac", filter=Q(carrierfac__status="ok"), distinct=True
        )
    ).update(fac_count=F("actual_count"))


class Migration(migrations.Migration):
    dependencies = [
        (
            "peeringdb_server",
            "0151_carrier_fac_count_alter_environmentsetting_setting_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            populate_carrier_fac_counts, reverse_code=migrations.RunPython.noop
        ),
    ]
