# Generated by Django 5.2.14 on 2026-06-03 23:59

from django.db import migrations
from django.db.models import Count, F, Q


def populate_carrier_fac_counts(apps, schema_editor):
    Carrier = apps.get_model("peeringdb_server", "Carrier")

    CarrierFacility = apps.get_model("peeringdb_server", "CarrierFacility")

    for carrier in Carrier._default_manager.all():
        count = CarrierFacility._default_manager.filter(
            carrier_id=carrier.id, status="ok"
        ).count()
        if carrier.fac_count != count:
            carrier.fac_count = count
            carrier.save(update_fields=["fac_count"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "peeringdb_server",
            "0151_carrier_fac_count_alter_environmentsetting_setting_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            populate_carrier_fac_counts, reverse_code=migrations.RunPython.noop
        ),
    ]
