# Generated by Django 5.2.15 on 2026-06-16 15:32

import oauth2_provider.generators
import oauth2_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0152_merge_20260612_1252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="speed",
            field=models.PositiveIntegerField(verbose_name="Capacity (mbit/sec)"),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="speed",
            field=models.PositiveIntegerField(verbose_name="Capacity (mbit/sec)"),
        ),
        migrations.AlterField(
            model_name="oauthapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
            ),
        ),
    ]
