# Generated by Django 5.2.16 on 2026-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0155_populate_carrier_fac_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="irr_as_set_auto_prefix_candidate",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="network",
            name="irr_as_set_auto_prefix_checked",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="irr_as_set_cap_notified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="irr_as_set_notified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
