# Generated by Django 5.2.16 on 2026-08-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0156_network_irr_as_set_auto_prefix_candidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="irr_as_set_missing_since",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="irr_as_set_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Not yet verified"),
                    ("ok", "Verified present"),
                    ("moved", "Moved to another registry"),
                    ("gone", "Gone from every registry"),
                ],
                default="unknown",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="network",
            name="irr_as_set_verified",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="irr_as_set_verify_notified",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
