# Generated by Django 5.2.16 on 2026-08-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0157_network_irr_as_set_missing_since_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="irr_as_set",
            field=models.CharField(
                blank=True,
                help_text="Reference to an AS-SET in Internet Routing Registry (IRR)",
                max_length=255,
                verbose_name="IRR as-set",
            ),
        ),
    ]
