# Generated by Django 5.2.16 on 2026-08-20 07:39

import django.core.validators
import django.utils.timezone
import django_countries.fields
import django_inet.models
import django_peeringdb.fields
import django_peeringdb.models.abstract
from django.db import migrations, models

import peeringdb_server.validators


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0158_alter_network_irr_as_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="aka",
            field=models.CharField(
                blank=True,
                help_text="Other names this record is commonly known by",
                max_length=255,
                null=True,
                verbose_name="Also Known As",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="name",
            field=models.CharField(
                help_text="Name of the campus, unique across PeeringDB",
                max_length=255,
                unique=True,
                verbose_name="Campus Name",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="name_long",
            field=models.CharField(
                blank=True,
                help_text="Full or legal name, where it differs from the short name",
                max_length=255,
                null=True,
                verbose_name="Long Name",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Public notes, displayed on the record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="social_media",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media presence, as a list of service and identifier pairs",
                verbose_name="Social Media",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="website",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                default="",
                help_text="Website of the campus",
                max_length=255,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="aka",
            field=models.CharField(
                blank=True,
                help_text="Other names this record is commonly known by",
                max_length=255,
                verbose_name="Also Known As",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="name",
            field=models.CharField(
                help_text="Name of the carrier, unique across PeeringDB",
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="name_long",
            field=models.CharField(
                blank=True,
                help_text="Full or legal name, where it differs from the short name",
                max_length=255,
                verbose_name="Long Name",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Public notes, displayed on the record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="social_media",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media presence, as a list of service and identifier pairs",
                verbose_name="Social Media",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="website",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                default="",
                help_text="Website of the carrier",
                max_length=255,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="address1",
            field=models.CharField(
                blank=True,
                help_text="First line of the street address",
                max_length=255,
                verbose_name="Address 1",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="address2",
            field=models.CharField(
                blank=True,
                help_text="Second line of the street address, if needed",
                max_length=255,
                verbose_name="Address 2",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="aka",
            field=models.CharField(
                blank=True,
                help_text="Other names this record is commonly known by",
                max_length=255,
                verbose_name="Also Known As",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City of the postal address",
                max_length=255,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="clli",
            field=models.CharField(
                blank=True,
                help_text="Common Language Location Identifier code for this facility",
                max_length=18,
                verbose_name="CLLI Code",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Two-letter ISO 3166-1 alpha-2 country code",
                max_length=2,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="floor",
            field=models.CharField(
                blank=True,
                help_text="Floor within the building",
                max_length=255,
                verbose_name="Floor",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude in decimal degrees, derived by geocoding the postal address",
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude in decimal degrees, derived by geocoding the postal address",
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(
                help_text="Name of the facility, unique across PeeringDB",
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name_long",
            field=models.CharField(
                blank=True,
                help_text="Full or legal name, where it differs from the short name",
                max_length=255,
                verbose_name="Long Name",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Public notes, displayed on the record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="npanxx",
            field=models.CharField(
                blank=True,
                help_text="North American Numbering Plan area code and exchange prefix serving this facility, as NPA-NXX",
                max_length=21,
                verbose_name="NPA-NXX",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="region_continent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("North America", "North America"),
                    ("Asia Pacific", "Asia Pacific"),
                    ("Europe", "Europe"),
                    ("South America", "South America"),
                    ("Africa", "Africa"),
                    ("Australia", "Australia"),
                    ("Middle East", "Middle East"),
                ],
                help_text="Continental region, derived from the country of the address",
                max_length=255,
                null=True,
                verbose_name="Continental Region",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="rencode",
            field=models.CharField(
                blank=True,
                help_text="Obsolete. Read-only; values submitted on create or update are ignored",
                max_length=18,
                verbose_name="Rencode",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="sales_email",
            field=models.EmailField(
                blank=True,
                help_text="Address to send sales questions about this facility",
                max_length=254,
                verbose_name="Sales Email",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="social_media",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media presence, as a list of service and identifier pairs",
                verbose_name="Social Media",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State, province or region of the postal address",
                max_length=255,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="status_dashboard",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                help_text="URL of a public status or outage dashboard for this facility",
                max_length=255,
                null=True,
                verbose_name="Status Dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="suite",
            field=models.CharField(
                blank=True,
                help_text="Suite or unit within the building",
                max_length=255,
                verbose_name="Suite",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="tech_email",
            field=models.EmailField(
                blank=True,
                help_text="Address to send technical questions about this facility",
                max_length=254,
                verbose_name="Technical Email",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="website",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Website of the facility",
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Postal code of the postal address",
                max_length=48,
                verbose_name="Zip-Code",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="aka",
            field=models.CharField(
                blank=True,
                help_text="Other names this record is commonly known by",
                max_length=255,
                verbose_name="Also Known As",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="city",
            field=models.CharField(
                help_text="City this exchange is based in",
                max_length=192,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="country",
            field=django_countries.fields.CountryField(
                help_text="Two-letter ISO 3166-1 alpha-2 code of the country this exchange is based in",
                max_length=2,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="ixf_last_import",
            field=models.DateTimeField(
                blank=True,
                help_text="Time this exchange's IX-F member export was last imported. Read-only",
                null=True,
                verbose_name="IX-F Last Import",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="ixf_net_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of networks seen in this exchange's IX-F member export. Read-only",
                verbose_name="IX-F Network Count",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="media",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Ethernet"),
                    ("ATM", "ATM"),
                    ("Multiple", "Multiple"),
                ],
                default="Ethernet",
                help_text="Obsolete. The PeeringDB API always reports `Ethernet` here regardless of the stored value; the field is deprecated and no longer describes the physical media offered at the exchange",
                max_length=128,
                verbose_name="Media Type",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="name",
            field=models.CharField(
                help_text="Name of the exchange, unique across PeeringDB",
                max_length=64,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="name_long",
            field=models.CharField(
                blank=True,
                help_text="Full or legal name, where it differs from the short name",
                max_length=255,
                verbose_name="Long Name",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Public notes, displayed on the record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="policy_email",
            field=models.EmailField(
                blank=True,
                help_text="Address to send peering requests for this exchange",
                max_length=254,
                verbose_name="Policy Email",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="proto_ipv6",
            field=models.BooleanField(
                default=False,
                help_text="Whether this exchange supports unicast IPv6. The PeeringDB API does not read this column: it derives the value from the LAN's active IPv6 prefixes and ignores values submitted on create or update",
                verbose_name="Unicast IPv6",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="proto_multicast",
            field=models.BooleanField(
                default=False,
                help_text="Whether this exchange supports multicast",
                verbose_name="Multicast",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="proto_unicast",
            field=models.BooleanField(
                default=False,
                help_text="Whether this exchange supports unicast IPv4. The PeeringDB API does not read this column: it derives the value from the LAN's active IPv4 prefixes and ignores values submitted on create or update",
                verbose_name="Unicast IPv4",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="region_continent",
            field=models.CharField(
                choices=[
                    ("North America", "North America"),
                    ("Asia Pacific", "Asia Pacific"),
                    ("Europe", "Europe"),
                    ("South America", "South America"),
                    ("Africa", "Africa"),
                    ("Australia", "Australia"),
                    ("Middle East", "Middle East"),
                ],
                help_text="Continental region this exchange operates in",
                max_length=255,
                verbose_name="Continental Region",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="sales_email",
            field=models.EmailField(
                blank=True,
                help_text="Address to send sales questions about this exchange",
                max_length=254,
                verbose_name="Sales Email",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="service_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Disclosed"),
                    ("Not Disclosed", "Not Disclosed"),
                    ("Best Effort (no SLA)", "Best Effort (no SLA)"),
                    ("Normal Business Hours", "Normal Business Hours"),
                    ("24/7 Support", "24/7 Support"),
                ],
                default="Not Disclosed",
                help_text="Level of support this exchange offers its participants",
                max_length=60,
                verbose_name="Service Level",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="social_media",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media presence, as a list of service and identifier pairs",
                verbose_name="Social Media",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="status_dashboard",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                help_text="URL of a public status or outage dashboard for this exchange",
                max_length=255,
                null=True,
                verbose_name="Status Dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="tech_email",
            field=models.EmailField(
                blank=True,
                help_text="Address to send technical questions about this exchange",
                max_length=254,
                verbose_name="Technical Email",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Disclosed"),
                    ("Not Disclosed", "Not Disclosed"),
                    ("No Commercial Terms", "No Commercial Terms"),
                    ("Bundled With Other Services", "Bundled With Other Services"),
                    ("Non-recurring Fees Only", "Non-recurring Fees Only"),
                    ("Recurring Fees", "Recurring Fees"),
                ],
                default="Not Disclosed",
                help_text="Commercial terms for participating in this exchange",
                max_length=60,
                verbose_name="Terms",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="url_stats",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                help_text="URL of public traffic statistics for this exchange",
                max_length=255,
                verbose_name="Traffic Stats Website",
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="website",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                default="",
                help_text="Website of the exchange",
                max_length=255,
                verbose_name="Company Website",
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="asn",
            field=django_inet.models.ASNField(
                help_text="Autonomous System Number of the connected network",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="ASN",
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="bfd_support",
            field=models.BooleanField(
                default=False,
                help_text="Whether this connection supports Bidirectional Forwarding Detection",
                verbose_name="BFD support",
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="ipaddr4",
            field=django_inet.models.IPAddressField(
                blank=True,
                help_text="IPv4 address of this connection, which must fall within one of the LAN's IPv4 prefixes",
                max_length=39,
                null=True,
                verbose_name="IPv4",
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="ipaddr6",
            field=django_inet.models.IPAddressField(
                blank=True,
                help_text="IPv6 address of this connection, which must fall within one of the LAN's IPv6 prefixes",
                max_length=39,
                null=True,
                verbose_name="IPv6",
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Public notes, displayed on the record",
                max_length=255,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="operational",
            field=models.BooleanField(
                default=True,
                help_text="Whether this connection is operational",
                verbose_name="Operational",
            ),
        ),
        migrations.AlterField(
            model_name="ixfmemberdata",
            name="speed",
            field=models.PositiveIntegerField(
                help_text="Capacity of this connection in Mbit/sec",
                verbose_name="Capacity (mbit/sec)",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="arp_sponge",
            field=django_inet.models.MacAddressField(
                blank=True,
                help_text="MAC address used by this LAN for ARP sponging",
                max_length=17,
                null=True,
                unique=True,
                verbose_name="ARP sponging MAC",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="descr",
            field=models.TextField(
                blank=True,
                help_text="Description of the exchange LAN",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="dot1q_support",
            field=models.BooleanField(
                default=False,
                help_text="Obsolete. The PeeringDB API always reports `false` here regardless of the stored value; the field is deprecated and no longer describes 802.1Q VLAN tagging support",
                verbose_name="802.1Q",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="ixf_ixp_import_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the IX-F member export at `ixf_ixp_member_list_url` is imported automatically for this LAN",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="ixf_ixp_member_list_url",
            field=models.URLField(
                blank=True,
                help_text="URL of this LAN's IX-F member export feed",
                null=True,
                verbose_name="IX-F Member Export URL",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="ixf_ixp_member_list_url_visible",
            field=models.CharField(
                choices=[
                    ("Private", "Private"),
                    ("Users", "Users"),
                    ("Public", "Public"),
                ],
                default="Private",
                help_text="Who may see `ixf_ixp_member_list_url`: `Public` anyone, `Users` authenticated users only, `Private` the owning organization only",
                max_length=64,
                verbose_name="IX-F Member Export URL Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="mtu",
            field=models.PositiveIntegerField(
                choices=[(1500, "1500"), (9000, "9000")],
                default=1500,
                help_text="Maximum transmission unit offered on this LAN, in bytes",
                verbose_name="MTU",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the exchange LAN",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="rs_asn",
            field=django_inet.models.ASNField(
                blank=True,
                default=0,
                help_text="Autonomous System Number of this LAN's route server",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Route Server ASN",
            ),
        ),
        migrations.AlterField(
            model_name="ixlan",
            name="vlan",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="VLAN id for this LAN. Not exposed via the API",
                null=True,
                verbose_name="VLAN",
            ),
        ),
        migrations.AlterField(
            model_name="ixlanprefix",
            name="in_dfz",
            field=models.BooleanField(
                default=True,
                help_text="Whether this prefix is routed in the default-free zone",
            ),
        ),
        migrations.AlterField(
            model_name="ixlanprefix",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Public notes, displayed on the record",
                max_length=255,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="ixlanprefix",
            name="prefix",
            field=django_inet.models.IPNetworkField(
                help_text="IP prefix assigned to the exchange LAN, in CIDR notation. Unique across PeeringDB",
                max_length=43,
                unique=True,
                verbose_name="Prefix",
            ),
        ),
        migrations.AlterField(
            model_name="ixlanprefix",
            name="protocol",
            field=models.CharField(
                choices=[("IPv4", "IPv4"), ("IPv6", "IPv6")],
                help_text="IP protocol version of this prefix",
                max_length=64,
                verbose_name="Protocol",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="aka",
            field=models.CharField(
                blank=True,
                help_text="Other names this record is commonly known by",
                max_length=255,
                verbose_name="Also Known As",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="asn",
            field=django_inet.models.ASNField(
                help_text="Autonomous System Number for this network. Cannot be changed after creation",
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="ASN",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="info_ipv6",
            field=models.BooleanField(
                default=False,
                help_text="Whether this network supports unicast IPv6",
                verbose_name="Unicast IPv6",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="info_multicast",
            field=models.BooleanField(
                default=False,
                help_text="Whether this network supports multicast",
                verbose_name="Multicast",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="info_ratio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Disclosed"),
                    ("Not Disclosed", "Not Disclosed"),
                    ("Heavy Outbound", "Heavy Outbound"),
                    ("Mostly Outbound", "Mostly Outbound"),
                    ("Balanced", "Balanced"),
                    ("Mostly Inbound", "Mostly Inbound"),
                    ("Heavy Inbound", "Heavy Inbound"),
                ],
                default="Not Disclosed",
                help_text="Self-classified ratio of outbound to inbound traffic for this network",
                max_length=45,
                verbose_name="Traffic Ratios",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="info_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Disclosed"),
                    ("Not Disclosed", "Not Disclosed"),
                    ("Regional", "Regional"),
                    ("North America", "North America"),
                    ("Asia Pacific", "Asia Pacific"),
                    ("Europe", "Europe"),
                    ("South America", "South America"),
                    ("Africa", "Africa"),
                    ("Australia", "Australia"),
                    ("Middle East", "Middle East"),
                    ("Global", "Global"),
                ],
                default="Not Disclosed",
                help_text="Self-classified geographic reach of this network",
                max_length=39,
                verbose_name="Geographic Scope",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="info_types",
            field=django_peeringdb.fields.MultipleChoiceField(
                blank=True,
                choices=[
                    ("NSP", "NSP"),
                    ("Content", "Content"),
                    ("Cable/DSL/ISP", "Cable/DSL/ISP"),
                    ("Enterprise", "Enterprise"),
                    ("Educational/Research", "Educational/Research"),
                    ("Non-Profit", "Non-Profit"),
                    ("Route Server", "Route Server"),
                    ("Network Services", "Network Services"),
                    ("Route Collector", "Route Collector"),
                    ("Government", "Government"),
                ],
                help_text="Self-classified categories describing this network",
                max_length=255,
                verbose_name="Network Types",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="info_unicast",
            field=models.BooleanField(
                default=False,
                help_text="Whether this network supports unicast IPv4",
                verbose_name="Unicast IPv4",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="looking_glass",
            field=django_peeringdb.models.abstract.LG_URLField(
                blank=True,
                help_text="URL of this network's looking glass. Accepts http, https, telnet and ssh schemes",
                max_length=255,
                verbose_name="Looking Glass URL",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="name",
            field=models.CharField(
                help_text="Name of the network, unique across PeeringDB",
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="name_long",
            field=models.CharField(
                blank=True,
                help_text="Full or legal name, where it differs from the short name",
                max_length=255,
                verbose_name="Long Name",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="netfac_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Time the most recently changed facility presence (`netfac`) of this network was updated. Read-only",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="netixlan_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Time the most recently changed exchange connection (`netixlan`) of this network was updated. Read-only",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Public notes, displayed on the record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="notes_private",
            field=models.TextField(
                blank=True,
                help_text="Notes visible only to administrators of the owning organization. Not exposed via the API",
                verbose_name="Private notes",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="poc_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Time the most recently changed point of contact (`poc`) of this network was updated. Read-only",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="policy_contracts",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not Required", "Not Required"),
                    ("Private Only", "Private Only"),
                    ("Required", "Required"),
                ],
                help_text="Whether a signed contract is required to peer with this network",
                max_length=36,
                verbose_name="Contract Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="policy_locations",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not Required", "Not Required"),
                    ("Preferred", "Preferred"),
                    ("Required - US", "Required - US"),
                    ("Required - EU", "Required - EU"),
                    ("Required - International", "Required - International"),
                ],
                help_text="Whether this network requires peering at multiple locations, and in which region",
                max_length=72,
                verbose_name="Multiple Locations",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="policy_ratio",
            field=models.BooleanField(
                default=False,
                help_text="Whether this network enforces a traffic ratio requirement",
                verbose_name="Ratio Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="policy_url",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                help_text="URL of this network's published peering policy",
                max_length=255,
                verbose_name="Peering Policy",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="rir_status",
            field=models.CharField(
                default=None,
                help_text="Allocation status of this network's ASN according to RIR data, refreshed periodically. Read-only; the PeeringDB API exposes only `ok` or `null` here, not the more detailed status kept internally",
                max_length=255,
                null=True,
                verbose_name="RIR status",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="rir_status_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Time `rir_status` was last set. Read-only",
                null=True,
                verbose_name="RIR status updated",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="route_server",
            field=django_peeringdb.models.abstract.LG_URLField(
                blank=True,
                help_text="URL of this network's route server. Accepts http, https, telnet and ssh schemes",
                max_length=255,
                verbose_name="Route Server URL",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="social_media",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media presence, as a list of service and identifier pairs",
                verbose_name="Social Media",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="status_dashboard",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                help_text="URL of a public status or outage dashboard for this network",
                max_length=255,
                null=True,
                verbose_name="Status Dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="website",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                help_text="Website of the network",
                max_length=255,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="networkcontact",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for this contact",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="networkcontact",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the contact, which may be a person or a team",
                max_length=254,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="networkcontact",
            name="role",
            field=models.CharField(
                choices=[
                    ("Abuse", "Abuse"),
                    ("Maintenance", "Maintenance"),
                    ("Policy", "Policy"),
                    ("Technical", "Technical"),
                    ("NOC", "NOC"),
                    ("Public Relations", "Public Relations"),
                    ("Sales", "Sales"),
                ],
                help_text="Function this contact serves for the network",
                max_length=27,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="networkcontact",
            name="url",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                help_text="Website for this contact",
                max_length=255,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="networkcontact",
            name="visible",
            field=models.CharField(
                choices=[
                    ("Private", "Private"),
                    ("Users", "Users"),
                    ("Public", "Public"),
                ],
                default="Public",
                help_text="Who may see this contact: `Public` anyone, `Users` authenticated users only, `Private` the owning organization only. `Private` is no longer accepted on write by the PeeringDB API and remains only on legacy records",
                max_length=64,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="networkfacility",
            name="avail_atm",
            field=models.BooleanField(
                default=False,
                help_text="Whether ATM is available. Not exposed via the API",
                verbose_name="ATM",
            ),
        ),
        migrations.AlterField(
            model_name="networkfacility",
            name="avail_ethernet",
            field=models.BooleanField(
                default=False,
                help_text="Whether Ethernet is available. Not exposed via the API",
                verbose_name="Ethernet",
            ),
        ),
        migrations.AlterField(
            model_name="networkfacility",
            name="avail_sonet",
            field=models.BooleanField(
                default=False,
                help_text="Whether SONET is available. Not exposed via the API",
                verbose_name="SONET",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="asn",
            field=django_inet.models.ASNField(
                help_text="Autonomous System Number of the connected network",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="ASN",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="bfd_support",
            field=models.BooleanField(
                default=False,
                help_text="Whether this connection supports Bidirectional Forwarding Detection",
                verbose_name="BFD support",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="ipaddr4",
            field=django_inet.models.IPAddressField(
                blank=True,
                help_text="IPv4 address of this connection, which must fall within one of the LAN's IPv4 prefixes",
                max_length=39,
                null=True,
                verbose_name="IPv4",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="ipaddr6",
            field=django_inet.models.IPAddressField(
                blank=True,
                help_text="IPv6 address of this connection, which must fall within one of the LAN's IPv6 prefixes",
                max_length=39,
                null=True,
                verbose_name="IPv6",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="is_rs_peer",
            field=models.BooleanField(
                default=False,
                help_text="Whether this connection peers with the exchange's route server",
                verbose_name="RS peer",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Public notes, displayed on the record",
                max_length=255,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="operational",
            field=models.BooleanField(
                default=True,
                help_text="Whether this connection is operational",
                verbose_name="Operational",
            ),
        ),
        migrations.AlterField(
            model_name="networkixlan",
            name="speed",
            field=models.PositiveIntegerField(
                help_text="Capacity of this connection in Mbit/sec",
                verbose_name="Capacity (mbit/sec)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address1",
            field=models.CharField(
                blank=True,
                help_text="First line of the street address",
                max_length=255,
                verbose_name="Address 1",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address2",
            field=models.CharField(
                blank=True,
                help_text="Second line of the street address, if needed",
                max_length=255,
                verbose_name="Address 2",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="aka",
            field=models.CharField(
                blank=True,
                help_text="Other names this record is commonly known by",
                max_length=255,
                verbose_name="Also Known As",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City of the postal address",
                max_length=255,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Two-letter ISO 3166-1 alpha-2 country code",
                max_length=2,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="floor",
            field=models.CharField(
                blank=True,
                help_text="Floor within the building",
                max_length=255,
                verbose_name="Floor",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude in decimal degrees, derived by geocoding the postal address",
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude in decimal degrees, derived by geocoding the postal address",
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="Name of the organization, unique across PeeringDB",
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_long",
            field=models.CharField(
                blank=True,
                help_text="Full or legal name, where it differs from the short name",
                max_length=255,
                verbose_name="Long Name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Public notes, displayed on the record",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="social_media",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media presence, as a list of service and identifier pairs",
                verbose_name="Social Media",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State, province or region of the postal address",
                max_length=255,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="suite",
            field=models.CharField(
                blank=True,
                help_text="Suite or unit within the building",
                max_length=255,
                verbose_name="Suite",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=django_peeringdb.models.abstract.URLField(
                blank=True,
                default="",
                help_text="Website of the organization",
                max_length=255,
                verbose_name="Website",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="zipcode",
            field=models.CharField(
                blank=True,
                help_text="Postal code of the postal address",
                max_length=48,
                verbose_name="Zip-Code",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Time this user account was registered",
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Given name of the user",
                max_length=254,
                validators=[peeringdb_server.validators.validate_account_name],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Family name of the user",
                max_length=254,
                validators=[peeringdb_server.validators.validate_account_name],
                verbose_name="last name",
            ),
        ),
    ]
