# Generated by Django 5.2.16 on 2026-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0159_facility_location_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="location_method",
            field=models.CharField(
                blank=True,
                choices=[("google", "Google place"), ("map", "Map pin")],
                default="",
                editable=False,
                max_length=16,
            ),
        ),
    ]
