# Generated by Django 1.11.4 on 2018-03-26 19:55


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0012_deskpro"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locale",
            field=models.CharField(
                blank=True, max_length=62, null=True, verbose_name="language"
            ),
        ),
    ]
