# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeringdb_server", "0021_sponsorship_drop_single_org_relation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ixlan",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
