# Generated by Django 2.2.9 on 2020-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0032_net_lg_rs_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="sales_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="facility",
            name="sales_phone",
            field=models.CharField(blank=True, max_length=192),
        ),
        migrations.AddField(
            model_name="facility",
            name="tech_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="facility",
            name="tech_phone",
            field=models.CharField(blank=True, max_length=192),
        ),
    ]
