# Generated by Django 2.2.13 on 2020-07-03 08:26

import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
import django_inet.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0037_netixlan_ipaddr_dedupe"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="networkixlan",
            constraint=models.UniqueConstraint(
                fields=("ipaddr4",), name="unique_ipaddr4"
            ),
        ),
        migrations.AddConstraint(
            model_name="networkixlan",
            constraint=models.UniqueConstraint(
                fields=("ipaddr6",), name="unique_ipaddr6"
            ),
        ),
    ]
