# Generated by Django 2.2.13 on 2020-07-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0037_ixfmemberdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixfmemberdata',
            name='error',
            field=models.TextField(blank=True, help_text='Trying to apply data to peeringdb raised an issue', null=True),
        ),
        migrations.AddField(
            model_name='ixfmemberdata',
            name='ixlan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ixf_set', to='peeringdb_server.IXLan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ixfmemberdata',
            name='data',
            field=models.TextField(default='{}', help_text='JSON snapshot of the ix-f member data that created this entry'),
        ),
    ]
