# Generated by Django 2.2.13 on 2020-07-08 20:48

import django_countries.fields
import django_inet.models
import django_peeringdb.models.abstract
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0038_netixlan_ipaddr_unique"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DuplicateIPNetworkIXLan",
        )
    ]
