# Generated by Django 2.2.13 on 2020-07-03 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0040_ixf_member_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixfmemberdata',
            options={'verbose_name': 'IXF Member Data', 'verbose_name_plural': 'IXF Member Data'},
        ),
        migrations.AddField(
            model_name='ixfmemberdata',
            name='fetched',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 12, 39, 7, 348836), verbose_name='Last Fetched'),
            preserve_default=False,
        ),
    ]
