# Generated by Django 2.2.13 on 2020-07-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0041_ixfmemberdata_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixfmemberdata',
            name='dismissed',
            field=models.BooleanField(default=False, help_text="Network's dismissal of this proposed change, which will hide it until from the customer facing network view"),
        ),
        migrations.AddField(
            model_name='ixfmemberdata',
            name='log',
            field=models.TextField(blank=True, help_text='Activity for this entry'),
        ),
    ]
