# Generated by Django 2.2.14 on 2020-07-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0049_deskrpo_ticket_additions"),
    ]

    operations = [
        migrations.AddField(
            model_name="ixlan",
            name="ixf_ixp_import_protocol_conflict",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="IX has been sending IP addresses for protocol not supported by network",
                null=True,
                verbose_name="IX-F sent IPs for unsupported protocol",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="allow_ixp_update",
            field=models.BooleanField(
                default=False,
                help_text="Sepcifies whether an IXP is allowed to add a netixlan entry for this network via their ixp_member data",
            ),
        ),
    ]
