# Generated by Django 2.2.17 on 2020-11-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0055_update_network_type_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskProTicketCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_set', to='peeringdb_server.DeskProTicket')),
            ],
            options={
                'verbose_name': 'DeskPRO Ticket CC Contact',
                'verbose_name_plural': 'Deskpro Ticket CC Contacts',
                'unique_together': {('ticket', 'email')},
            },
        ),
    ]
