# Generated by Django 2.2.17 on 2020-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0056_add_last_updated_fields_to_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="floor",
            field=models.CharField(blank=True, max_length=255, verbose_name="Floor"),
        ),
        migrations.AddField(
            model_name="facility",
            name="suite",
            field=models.CharField(blank=True, max_length=255, verbose_name="Suite"),
        ),
        migrations.AddField(
            model_name="organization",
            name="floor",
            field=models.CharField(blank=True, max_length=255, verbose_name="Floor"),
        ),
        migrations.AddField(
            model_name="organization",
            name="suite",
            field=models.CharField(blank=True, max_length=255, verbose_name="Suite"),
        ),
        migrations.AddField(
            model_name="organization",
            name="geocode_date",
            field=models.DateTimeField(
                blank=True, help_text="Last time of attempted geocode", null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="geocode_error",
            field=models.TextField(
                blank=True,
                help_text="Error message of previous geocode attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="geocode_status",
            field=models.BooleanField(
                default=False,
                help_text="Has this object's latitude and longitude been synchronized to its address fields",
            ),
        ),
    ]
