# Generated by Django 2.2.17 on 2021-01-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0058_deskpro_cc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ixfimportemail",
            options={
                "verbose_name": "IX-F Import Email",
                "verbose_name_plural": "IX-F Import Emails",
            },
        ),
        migrations.AlterModelOptions(
            name="ixfmemberdata",
            options={
                "verbose_name": "IX-F Member Data",
                "verbose_name_plural": "IX-F Member Data",
            },
        ),
        migrations.AlterModelOptions(
            name="ixlanixfmemberimportlog",
            options={
                "verbose_name": "IX-F Import Log",
                "verbose_name_plural": "IX-F Import Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="ixlanixfmemberimportlogentry",
            options={
                "verbose_name": "IX-F Import Log Entry",
                "verbose_name_plural": "IX-F Import Log Entries",
            },
        ),
    ]
