# Generated by Django 2.2.18 on 2021-03-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeringdb_server", "0063_populate_last_update_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                max_digits=18,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                max_digits=18,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                max_digits=18,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                max_digits=18,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
