# Generated by Django 2.2.18 on 2021-03-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peeringdb_server", "0064_alter_geo_lat_long_decimals"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="aka",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Also Known As"
            ),
        ),
    ]
