# Generated by Django 2.2.24 on 2021-06-25 11:01

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0071_populate_obj_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoCoordinateCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                ("fetched", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Geocoordinate Cache",
                "verbose_name_plural": "Geocoordinate Cache Entries",
                "db_table": "peeringdb_geocoord_cache",
            },
        ),
    ]
