# Generated by Django 3.2.9 on 2022-01-06 12:54

import django.core.validators
import django_inet.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeringdb_server", "0079_org_add_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentsetting",
            name="setting",
            field=models.CharField(
                choices=[
                    ("API_THROTTLE_RATE_ANON", "API: Anonymous user API throttle rate"),
                    (
                        "API_THROTTLE_RATE_USER",
                        "API: Authenticated user API throttle rate",
                    ),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
