# Generated by Django 3.2.9 on 2021-11-05 13:15

import django.core.validators
from django.db import migrations, models
import django_inet.models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0080_webauthn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ixfmemberdata',
            name='asn',
            field=django_inet.models.ASNField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='ASN'),
        ),
        migrations.AlterField(
            model_name='ixlan',
            name='rs_asn',
            field=django_inet.models.ASNField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Route Server ASN'),
        ),
        migrations.AlterField(
            model_name='network',
            name='asn',
            field=django_inet.models.ASNField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='ASN'),
        ),
        migrations.AlterField(
            model_name='networkfacility',
            name='local_asn',
            field=django_inet.models.ASNField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Local ASN'),
        ),
        migrations.AlterField(
            model_name='networkixlan',
            name='asn',
            field=django_inet.models.ASNField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='ASN'),
        ),
        migrations.AlterField(
            model_name='userhandle',
            name='handle',
            field=models.CharField(blank=True, db_index=True, help_text='Unqiue user handle to be used to map users to their Webauthn credentials, only set if user has registered one or more security keys. Will be unique random 64 bytes', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userorgaffiliationrequest',
            name='asn',
            field=django_inet.models.ASNField(blank=True, help_text='The ASN entered by the user', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
    ]
