# Generated by Django 3.2.9 on 2021-11-05 17:03

import django.core.validators
from django.db import migrations
import django_inet.models


class Migration(migrations.Migration):

    dependencies = [
        ('peeringdb_server', '0081_webauthn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Webauthn Challenge', 'verbose_name_plural': 'Webauthn Challenges'},
        ),
        migrations.AlterModelOptions(
            name='securitykey',
            options={'verbose_name': 'Webauthn Security Key', 'verbose_name_plural': 'Webauthn Security Keys'},
        ),
        migrations.RenameField(
            model_name='securitykey',
            old_name='credetnial_public_key',
            new_name='credential_public_key',
        ),
        migrations.AlterField(
            model_name='ixfmemberdata',
            name='asn',
            field=django_inet.models.ASNField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='ASN'),
        ),
        migrations.AlterField(
            model_name='ixlan',
            name='rs_asn',
            field=django_inet.models.ASNField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Route Server ASN'),
        ),
        migrations.AlterField(
            model_name='network',
            name='asn',
            field=django_inet.models.ASNField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='ASN'),
        ),
        migrations.AlterField(
            model_name='networkfacility',
            name='local_asn',
            field=django_inet.models.ASNField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Local ASN'),
        ),
        migrations.AlterField(
            model_name='networkixlan',
            name='asn',
            field=django_inet.models.ASNField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='ASN'),
        ),
        migrations.AlterField(
            model_name='userorgaffiliationrequest',
            name='asn',
            field=django_inet.models.ASNField(blank=True, help_text='The ASN entered by the user', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
    ]
