# Generated by Django 3.2.13 on 2022-05-13 16:23

from django.db import migrations, utils


def fix_constraints(apps, schema_editor):

    try:

        migrations.RunSQL(
            "alter table oauth2_provider_grant drop foreign key `oauth2_provider_grant_application_id_81923564_fk`"
        )
        migrations.RunSQL(
            "alter table oauth2_provider_accesstoken drop foreign key `oauth2_provider_accesstoken_application_id_b22886e1_fk`;"
        )
        migrations.RunSQL(
            "alter table oauth2_provider_idtoken drop foreign key `oauth2_provider_idto_application_id_08c5ff4f_fk_oauth2_pr`;"
        )
        migrations.RunSQL(
            "alter table oauth2_provider_refreshtoken drop foreign key `oauth2_provider_refreshtoken_application_id_2d1c311b_fk`;"
        )
        migrations.RunSQL(
            "alter table oauth2_provider_grant add constraint oauth2_provider_grant_application_id_81923564_fk foreign key (`application_id`) REFERENCES `peeringdb_oauth_application` (`id`) ON DELETE CASCADE;"
        )
        migrations.RunSQL(
            "alter table oauth2_provider_accesstoken add constraint oauth2_provider_accesstoken_application_id_b22886e1_fk foreign key (`application_id`) REFERENCES `peeringdb_oauth_application` (`id`) ON DELETE CASCADE;"
        )
        migrations.RunSQL(
            "alter table oauth2_provider_idtoken add constraint oauth2_provider_idto_application_id_08c5ff4f_fk_oauth2_pr foreign key (`application_id`) REFERENCES `peeringdb_oauth_application` (`id`) ON DELETE CASCADE;"
        )
        migrations.RunSQL(
            "alter table oauth2_provider_refreshtoken add constraint oauth2_provider_refreshtoken_application_id_2d1c311b_fk foreign key (`application_id`) REFERENCES `peeringdb_oauth_application` (`id`) ON DELETE CASCADE;"
        )

    except utils.OperationalError as exc:
        if "Can't DROP" in str(exc):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("peeringdb_server", "0086_auto_20220510_0949"),
    ]

    operations = [migrations.RunPython(fix_constraints, migrations.RunPython.noop)]
